#app
server:
    port: 10012

#spring
spring:
  devtools:
    restart:
      enabled: false

  application:
    name: cloud_web_template
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    time-zone : Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    database: 3  
    host: 127.0.0.1
    port: 6379
    password:  
    pool:
      max-active: 8  
      max-wait: -1  
      max-idle: 8  
      min-idle: 0  
      timeout: 0  
        
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/saascloud?autoReconnect=true&amp;characterEncoding=UTF-8&amp;useUnicode=true
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
    
    second:
      url: jdbc:mysql://localhost:3306/test?autoReconnect=true&amp;characterEncoding=UTF-8&amp;useUnicode=true
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver  
    
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
            naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
              
    properties:
            hibernate:
                dialect : org.hibernate.dialect.MySQL5Dialect
 
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
##logging
logging:
  path: D:\\temp\\logs
  file: cloud_template.log
  level:
    root: DEBUG
    org.hibernate : ERROR
    org.thymeleaf : ERROR
    com.cloud.webtemplate : DEBUG
    org.apache.catalina.session.ManagerBase: warn


sso:
  type: client
  server.url: http://127.0.0.1:20010
  appID: im
  
jwt:
  token:
    secret:  pbsaasSecret0
    expiration: 604800
